### ISSUE TITLE
DDLogCWarn' is invalid in C99 error 

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [SVGKit/SVGKit#378]
For my Swift project, I'm installing SVGKit via CocoaPods. Here's my `Podfile`.

```
platform :ios, '8.0'
use_frameworks!

pod 'SVGKit'
```

The installation is successful. But when I try to build it, I get the following error in the _SVGHelperUtilities.m_ file (line 434).

**Implicit declaration of function 'DDLogCWarn' is invalid in C99**

I tried this with the `use_frameworks!` flag and without. Still the same error occurs. I'm using CocoaPods 0.39.0 with Xcode 7.1 beta.

**Comment by seltzered** [comment]
can you try installing SVGKit from the 2.x branch? The podfile in that branch should be up-to-date, and that branch has been updated to work with cocoalumberjack 2.0.

**Comment by Isuru-Nanayakkara** [comment]
It seems I don't have permission to add a branch like that.

```
platform :ios, '8.0'
use_frameworks!

pod 'SVGKit', :git => 'git@github.com:SVGKit/SVGKit.git', :branch => '2.x'
```

![screen shot 2015-11-08 at 11 50 23 pm](https://cloud.githubusercontent.com/assets/2551877/11021806/8dfe5268-8673-11e5-9c51-219e8bcb48ac.png)

**Comment by seltzered** [comment]
Try referencing the repository via the https url instead. see
https://guides.cocoapods.org/syntax/podfile.html#pod for more info.

On Sun, Nov 8, 2015 at 10:21 AM, Isuru Nanayakkara <notifications@github.com

**Comment by Isuru-Nanayakkara** [comment]
Yep, that seems to work. Thanks for the help!
